[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
peersaku_lending = "Peer111111111111111111111111111111111111111"
peersaku_credit = "Peer222222222222222222222222222222222222222"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 60000

[test.validator]
ledger = ".anchor-ledger"
bind_address = "127.0.0.1"

[scripts]
test = "pnpm mocha tests/**/*.js"
